barberia/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('checho.urls')),
]

checho/urls.py
from django.urls import path
from . import views

app_name='checho'

urlpatterns = [
    path('', views.index,name='index'),
    path('login/', views.login,name='login'),
    path('ingresar/', views.ingresar,name='ingresar'),
    path('cerraSesion/', views.cerraSesion,name='cerraSesion'),



#Datos de usuario----------------------------->

    path('registrarUser/', views.registrarUser,name='registrarUser'),
    path('guardarUser/', views.guardarUser,name='guardarUser'),
    path('listarClientes/', views.listarClientes,name='listarClientes'),
    path('eliminarCliente/<int:id>', views.eliminarCliente,name='eliminarCliente'),
    path('editarCliente/<int:id>', views.editarCliente,name='editarCliente'),
    path('guardarCliente/', views.guardarCliente,name='guardarCliente'),
    path('clientesBuscar/', views.clientesBuscar,name='clientesBuscar'),

    




#Datos del admin----------------------------->
    path('registrarAdmin/', views.registrarAdmin,name='registrarAdmin'),
    path('guardarAdmin/', views.guardarAdmin,name='guardarAdmin'),
    path('listarAdmin/', views.listarAdmin,name='listarAdmin'),
    path('eliminarAdmin/<int:id>', views.eliminarAdmin,name='eliminarAdmin'),
    path('editarAdmin/<int:id>', views.editarAdmin,name='editarAdmin'),
    path('guardadoAdmin/', views.guardadoAdmin,name='guardadoAdmin'),
    path('loginAdmin/', views.loginAdmin,name='loginAdmin'),
    path('logearAdmin/', views.logearAdmin,name='logearAdmin'),


    
    
    




#datos de empleado----------------------------->
    path('registrarEmpleado/', views.registrarEmpleado,name='registrarEmpleado'),
    path('guardarEmpleado/', views.guardarEmpleado,name='guardarEmpleado'),
    path('listarEmpleados/', views.listarEmpleados,name='listarEmpleados'),
    path('eliminarEmpleado/<int:id>', views.eliminarEmpleado,name='eliminarEmpleado'),
    path('editarEmpleado/<int:id>', views.editarEmpleado,name='editarEmpleado'),
    path('guardadoEmpleado/', views.guardadoEmpleado,name='guardadoEmpleado'),




#Datos Se Servicios -------------------------------->
path('registrarServicio/', views.registrarServicio,name='registrarServicio'),
path('guardarServicio/', views.guardarServicio,name='guardarServicio'),
path('listarServicios/', views.listarServicios,name='listarServicios'),
path('editarServicio/<int:id>', views.editarServicio,name='editarServicio'),
path('guardarEdicionServicio/', views.guardarEdicionServicio,name='guardarEdicionServicio'),
path('eliminarServicio/<int:id>', views.eliminarServicio,name='eliminarServicio'),
    


#Datos Citas
path('agendarCita/', views.agendarCita,name='agendarCita'),
path('guardarCita/', views.guardarCita,name='guardarCita'),
path('listarCita/', views.listarCita,name='listarCita'),
path('eliminarCita/<int:id>', views.eliminarCita,name='eliminarCita'),








]

checho/models.py
from django.db import models

# Create your models here.
class Servicios(models.Model):
    nombreServicio=models.CharField(max_length=255)
    precio=models.PositiveIntegerField()

    def __str__(self) -> str:
        return self.nombreServicio

class Clientes(models.Model):

    nombre=models.CharField(max_length=100)       
    apellido=models.CharField(max_length=100)       
    numeroTelefono=models.PositiveIntegerField()
    usuario=models.CharField(max_length=100)       
    contraseña=models.CharField(max_length=100)
    rol=models.CharField(max_length=100,default="cliente")


    def __str__(self) -> str:

        return f" {self.nombre} {self.apellido}  "


class Administradores(models.Model):

    nombre=models.CharField(max_length=100)       
    apellido=models.CharField(max_length=100)       
    numeroTelefono=models.PositiveIntegerField()
    usuario=models.CharField(max_length=100)
    contraseña=models.CharField(max_length=100)
    rol=models.CharField(max_length=100,default="administrador")

    def __str__(self) -> str:

        return f" {self.nombre} {self.apellido}  "        

class Empleados(models.Model):

    nombre=models.CharField(max_length=100)       
    apellido=models.CharField(max_length=100)       
    numeroTelefono=models.PositiveIntegerField()
    usuario=models.CharField(max_length=100)
    contraseña=models.CharField(max_length=100)
    rol=models.CharField(max_length=100,default="empleado")
    administrador=models.ForeignKey(Administradores,on_delete=models.CASCADE,null=True)

    def __str__(self) -> str:

        return f" {self.nombre} {self.apellido}  "

class Citas(models.Model):

    fecha=models.DateField(auto_now_add=False)
    hora=models.TimeField(auto_now_add=False)
    estado=models.BooleanField(default=True)
    cliente=models.ForeignKey(Clientes, on_delete=models.CASCADE,null=True)
    servicio=models.ForeignKey(Servicios, on_delete=models.CASCADE,null=True)
    empleado=models.ForeignKey(Empleados, on_delete=models.CASCADE,null=True)


    def __str__(self):

        return  f"   {self.fecha} {self.hora} {self.cliente}"

checho/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.db import IntegrityError
from django.shortcuts import render,redirect
from django.urls import reverse
from django.http import HttpResponse
from  .models import *
from django.core.paginator import Paginator


# Create your views here.
#return HttpResponseRedirect(reverse('territorio:aprendiz'))
def index(request):
    return render(request, 'index.html')

# Datos del login ------------------------------------------------------
def login(request):
    return render(request, 'login/login.html')

def ingresar(request):
    if request.method == "POST":
        try:
            #capturar datos del formulario
            use = request.POST["usua"]
            pasw = request.POST["clave"]
            
            #verificar si existe en base de datos
            q = Clientes.objects.get(usuario = use, contraseña = pasw)
            
            #crear la variable de sesion
            request.session["logueo"] = [q.id,q.usuario,q.rol]

            return redirect('checho:index')
        except Clientes.DoesNotExist:
            messages.error(request, "Usuario o contraseña incorrectos...")
            return redirect('checho:login')
    else:
        messages.warning(request, "Usted no envió datos...")
        return redirect('checho:login')

def cerraSesion(request):
    try:
        del request.session["logueo"]
        messages.success(request, "Sesión cerrada correctamente!")
    except Exception as e:
        messages.error(request, "Ocurrió un error, intente de nuevo...")
    
    return redirect('checho:index')


#datos del usuario o cliente -------------------------------->
def registrarUser(request):
    return render(request, 'usuario/registrarUser.html')

def guardarUser(request):
    try:
        if request.method == 'POST':
            nom=request.POST['nombre']
            apell=request.POST['apellido']
            numTel=request.POST['telefono']
            user=request.POST['user']
            contra=request.POST['passw']

            q=Clientes.objects.create(nombre=nom,apellido=apell,numeroTelefono=numTel,usuario=user,contraseña=contra)
            messages.success(request, 'Cliente agregado')

            return  redirect('checho:listarClientes')
        else:
            
            messages.warning(request, "Usted no envio datos ")
            return redirect('checho:listarClientes') 
    except Exception as e:
        messages.error(request, "Error: " + str(e))
        return redirect('checho:listarClientes')           
    

def listarClientes(request):
    q=Clientes.objects.all()
    pag = Paginator(q, 4)   #cinco registros por página
    page_number = request.GET.get('page')
        
        #sobreescribo el query
    q = pag.get_page(page_number)
        
    contexto = {'page_obj': q}
    return render(request,'usuario/listarUsuarios.html',contexto)


def eliminarCliente(request,id):
    try: 
        q=Clientes.objects.get(id=id)

        q.delete()
        messages.success(request, 'Cliente Eliminado')
        return redirect('checho:listarClientes') 
    except Exception as e:
        return HttpResponse(e)


def editarCliente(request,id):

    client=Clientes.objects.get(id=id)

    return render(request, 'usuario/edicionCliente.html',{'client':client})


def guardarCliente(request):

    try:
        if request.method == 'POST':
            nom=request.POST['nombre']
            ape=request.POST['apellido']
            tel=request.POST['telefono']
            id=request.POST['id']

            cliente=Clientes.objects.get(id=id)

            cliente.nombre = nom
            cliente.apellido =ape
            cliente.numeroTelefono=tel

            cliente.save()

            messages.success(request, 'Cliente agregado')

            return redirect('checho:listarClientes')

        else:
            
            messages.warning(request, "Usted no envio datos ")
            return redirect('checho:listarClientes')    

    except Exception as e:
        messages.error(request, "Error: " + str(e))
        return redirect('checho:listarClientes')

#datos de Empleado ----------------------------------->
def registrarEmpleado(request):
    admin=Administradores.objects.all()
    return render(request, 'empleado/registrarEmpleado.html',{'admin':admin})

def guardarEmpleado(request):
    
    try:
        if request.method == 'POST':
            nom=request.POST['nombre']
            apell=request.POST['apellido']
            numTel=request.POST['telefono']
            user=request.POST['user']
            contra=request.POST['passw']
            administrador=request.POST['admin']

            admin=Administradores.objects.get(id=administrador)
        
            q=Empleados.objects.create(nombre=nom,apellido=apell,numeroTelefono=numTel,usuario=user,contraseña=contra,administrador=admin)
            messages.success(request, 'Empleado agregado')
            return  redirect('checho:listarEmpleados')

        else:
            messages.warning(request, "Usted no envio datos ")
            return redirect('checho:listarEmpleados')    

    except Exception as e:
        messages.error(request, "Error: " + str(e))
        return redirect('checho:listarEmpleados')


def listarEmpleados(request):
    q=Empleados.objects.all()
    admin=Administradores.objects.all()
    pag = Paginator(q, 4)   #cinco registros por página
    page_number = request.GET.get('page')
        
        #sobreescribo el query
    q = pag.get_page(page_number)
        
    contexto = {'page_obj': q,'admin': admin}
    
    return render(request, 'empleado/listarEmpleados.html',contexto)    

def eliminarEmpleado(request, id):
    try:

        emple=Empleados.objects.get(id=id)

        emple.delete()
        messages.success(request, 'Empleado eliminado')
        return redirect('checho:listarEmpleados')

    except Exception as e:
        messages.error(request, "Error: " + str(e))
        return redirect('checho:listarEmpleados')


def editarEmpleado(request, id):


    emple=Empleados.objects.get(id=id)

    admin=Administradores.objects.all()

    return render(request, 'empleado/editarEmpleado.html', {'empleado': emple,'admin': admin})


def guardadoEmpleado(request):
    
    try:
        if request.method == 'POST':
            nom=request.POST['nombre']
            ape=request.POST['apellido']
            tel=request.POST['telefono']
            id=request.POST['id']
            admin=request.POST['admin']

            ad=Administradores.objects.get(id=admin)
            emple=Empleados.objects.get(id=id)

            emple.nombre=nom
            emple.apellido=ape
            emple.numeroTelefono=tel
            emple.administrador=ad

            emple.save()
            messages.success(request, 'Empleado Guardado')
            return  redirect('checho:listarEmpleados')
        else:
            messages.warning(request, "Usted no envio datos ")
            return redirect('checho:listarEmpleados')  
            
    except Exception as e:
        messages.error(request, "Error: " + str(e))
        return redirect('checho:listarEmpleados')

def clientesBuscar (request):
    if request.method == "POST":
        
        from django.db.models import Q
        
        q = Clientes.objects.filter(
            Q(nombre__icontains = request.POST["dato"]) | 
            Q(apellido__icontains = request.POST["dato"]) 
           
        )
        
        pag = Paginator(q, 4)   #cinco registros por página
        page_number = request.GET.get('page')
        
        #sobreescribo el query
        q = pag.get_page(page_number)
        
        contexto = {'page_obj': q, "dato_buscado": request.POST["dato"]}

        return render(request,'usuario/listarClientesAjax.html',contexto)
    else:
        messages.warning(request, "Usted no envió datos...")
        return redirect('checho:listarClientes')



#datos del Administrador ------------------------------>
def registrarAdmin(request):
    return render(request, 'admin/registrarAdmin.html')    
def loginAdmin(request):
    return render(request, 'login/loginAdmin.html')   

def logearAdmin(request):
    try:
        if request.method == 'POST':
            user=request.POST['u']
            passw=request.POST['p']

            q = Administradores.objects.get(usuario = user, contraseña = passw)
            request.session["logueo"] = [q.id,q.usuario,q.rol]
            messages.success(request, 'Bienvenido')
            return  redirect('checho:index')
        else:
            messages.warning(request, "usuario o contraseña incorrectos ")
            return redirect('checho:loginAdmin')

    except Exception as e:
        messages.error(request, "Error: " + str(e))
        return redirect('checho:loginAdmin')  


def guardarAdmin(request):
    try:
        if request.method == 'POST':
            nom=request.POST['nombre']
            apell=request.POST['apellido']
            numTel=request.POST['telefono']
            user=request.POST['user']
            contra=request.POST['passw']

            q=Administradores.objects.create(nombre=nom,apellido=apell,numeroTelefono=numTel,usuario=user,contraseña=contra)

            messages.success(request, 'Administrador Guardado')
            
            return  redirect('checho:listarAdmin')
        else:
            messages.warning(request, "Usted no envio datos ")
            return redirect('checho:listarAdmin')

    except Exception as e:
        messages.error(request, "Error: " + str(e))
        return redirect('checho:listarAdmin')  

def listarAdmin(request):

    q=Administradores.objects.all()
    pag = Paginator(q, 4)   #cinco registros por página
    page_number = request.GET.get('page')
        
        #sobreescribo el query
    q = pag.get_page(page_number)
        
    contexto = {'page_obj': q}

    return render(request, 'admin/listarAdmin.html', contexto)    
def eliminarAdmin(request,id):    
    try:

checho/templates/bases/base.html
{%load static%}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock%}</title>


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
        integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">

</head>

<body>
    <div class="contenedor">

        <header class=""></header>
        <div class="containerNav ">
            <nav class="navbar navbar-expand-lg bg-dark ">
                <div class="container-fluid">
                    <div><a class="navbar-brand text-light hoverNav  " href="#">CHECHO BARBERS</a></div>
                    <div>

                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon bg-secondary"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                                <li class="nav-item">
                                    <a class="nav-link active text-light hoverNav" aria-current="page"
                                        href="{% url 'checho:index' %}">INICIO</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active text-light hoverNav" aria-current="page" href="#">VER MIS
                                        CITAS</a>
                                </li>

                                <li class="nav-item dropdown text-light">
                                    <a class="nav-link dropdown-toggle text-light hoverNav" href="#" role="button"
                                        data-bs-toggle="dropdown" aria-expanded="false">
                                        SERVICIOS
                                    </a>
                                    <ul class="dropdown-menu tama2 ">
                                        <li><a class="dropdown-item" href="#">BARBAS</a></li>
                                        <li><a class="dropdown-item" href="#">CORTES</a></li>
                                        <li><a class="dropdown-item" href="#">TINTURAS</a></li>
                                    </ul>
                                </li>
                                {% if request.session.logueo.2 == 'administrador' %}
                                <li class="nav-item dropdown text-light">
                                    <a class="nav-link dropdown-toggle text-light hoverNav" href="#" role="button"
                                        data-bs-toggle="dropdown" aria-expanded="false">
                                        OPCIONES
                                    </a>
                                    <ul class="dropdown-menu tama2 ">
                                        <li><a class="dropdown-item" href="{% url 'checho:listarCita' %}">LISTAR
                                                CITAS</a></li>
                                        <li><a class="dropdown-item" href="{% url 'checho:listarServicios' %}">LISTAR
                                                SERVICIOS</a></li>
                                        <li><a class="dropdown-item" href="{% url 'checho:listarClientes' %}">LISTAR
                                                CLIENTES</a></li>
                                        <li><a class="dropdown-item" href="{% url 'checho:listarEmpleados' %}">LISTAR
                                                EMPLEADOS</a></li>
                                        <li><a class="dropdown-item" href="{% url 'checho:listarAdmin' %}">LISTAR
                                                ADMINISTRADORES</a></li>
                                    </ul>
                                </li>
                                
                                <li class="nav-item dropdown text-light">
                                    <a class="nav-link dropdown-toggle text-light hoverNav" href="#" role="button"
                                        data-bs-toggle="dropdown" aria-expanded="false">
                                        OTROS
                                    </a>
                                    <ul class="dropdown-menu tama2 ">
                                        <li><a class="dropdown-item"
                                                href="{% url 'checho:registrarEmpleado' %}">REGISTRAR EMPLEADO</a></li>
                                        <li><a class="dropdown-item" href="{% url 'checho:registrarAdmin' %}">REGISTRAR
                                                ADMIN</a></li>
                                        <li><a class="dropdown-item"
                                                href="{% url 'checho:registrarServicio' %}">REGISTRAR SERVICIOS</a></li>
                                    </ul>
                                </li>
                                {% endif %}
                                <li class="nav-item text-light">
                                    <a class="nav-link text-light hoverNav" href="{% url 'checho:agendarCita' %}">AGENDA
                                        TU CITA</a>
                                </li>

                                <li class="nav-item text-light me-5">
                                    <a class="nav-link text-light hoverNav" href="#contacto">CONTACTO</a>
                                </li>


                                {% if request.session.logueo %}
                                <li class="nav-item text-light">
                                    <a class="nav-link text-light hoverNav" href="{% url 'checho:cerraSesion' %}">CERRAR
                                        SESION</a>
                                </li>
                                {% else %}
                                <li class="nav-item text-light">
                                    <a class="nav-link text-light hoverNav" href="{% url 'checho:login' %}">INICIO
                                        SESION</a>
                                </li>
                                <li class="nav-item text-light">
                                    <a class="nav-link text-light hoverNav"
                                        href="{% url 'checho:registrarUser' %}">REGISTRARSE</a>
                                </li>

                                {% endif %}
                                
                                



                            </ul>

                        </div>
                    </div>
                </div>
            </nav>
        </div>
    </div>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{% if message.tags != 'error' %}{{ message.tags }}{% else %}danger{% endif %} alert-dismissible fade show"
        role="alert">{{ message }}<button type="button" class="btn-close" data-bs-dismiss="alert"
            aria-label="Close"></button></div>
    {% endfor %}
    {% endif %}

    <main>{%block content %}{%endblock%}</main>





    <footer style="height: 25vh ; ">
        <div class="row">

            <div class="col  col-sm-12 col-md-4 col-lg-4 col-xl-4 ">
                <h5>CHECHO BARBER</h5>
                <p>Copyright © 2022 Todos los derechos reservados</p>

            </div>
            <div class="col  col-sm-12 col-md-4 col-lg-4 col-xl-4">
                <h5 id="contacto">CONTACTO</h5>
                <p> Telefono (3714526)</p>
                <p>Gmail (chechobarber@gmail.com)</p>

            </div>
            <div class="col  col-sm-12 col-md-4 col-lg-4 col-xl-4">
                <h5>UBICACION</h5>
                <a target="_blank" href=""><img src="{% static 'img/maps.jpg' %}" alt="maps" id="im4"></a>
            </div>
        </div>
    </footer>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js'%}"></script>

    <script src="{%static 'js/controller.js' %}"></script><script src="{% static 'js/jquery-3.6.1.min.js'%}"></script>
</body>

</html>