barberia/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('checho.urls')),
]

checho/urls.py
from django.urls import path
from . import views

app_name='checho'

urlpatterns = [
    path('', views.index,name='index'),
    path('login/', views.login,name='login'),
    path('ingresar/', views.ingresar,name='ingresar'),
    path('cerraSesion/', views.cerraSesion,name='cerraSesion'),



#Datos de usuario----------------------------->

    path('registrarUser/', views.registrarUser,name='registrarUser'),
    path('guardarUser/', views.guardarUser,name='guardarUser'),
    path('listarClientes/', views.listarClientes,name='listarClientes'),
    path('eliminarCliente/<int:id>', views.eliminarCliente,name='eliminarCliente'),
    path('editarCliente/<int:id>', views.editarCliente,name='editarCliente'),
    path('guardarCliente/', views.guardarCliente,name='guardarCliente'),
    path('clientesBuscar/', views.clientesBuscar,name='clientesBuscar'),

    




#Datos del admin----------------------------->
    path('registrarAdmin/', views.registrarAdmin,name='registrarAdmin'),
    path('guardarAdmin/', views.guardarAdmin,name='guardarAdmin'),
    path('listarAdmin/', views.listarAdmin,name='listarAdmin'),
    path('eliminarAdmin/<int:id>', views.eliminarAdmin,name='eliminarAdmin'),
    path('editarAdmin/<int:id>', views.editarAdmin,name='editarAdmin'),
    path('guardadoAdmin/', views.guardadoAdmin,name='guardadoAdmin'),
    path('loginAdmin/', views.loginAdmin,name='loginAdmin'),
    path('logearAdmin/', views.logearAdmin,name='logearAdmin'),


    
    
    




#datos de empleado----------------------------->
    path('registrarEmpleado/', views.registrarEmpleado,name='registrarEmpleado'),
    path('guardarEmpleado/', views.guardarEmpleado,name='guardarEmpleado'),
    path('listarEmpleados/', views.listarEmpleados,name='listarEmpleados'),
    path('eliminarEmpleado/<int:id>', views.eliminarEmpleado,name='eliminarEmpleado'),
    path('editarEmpleado/<int:id>', views.editarEmpleado,name='editarEmpleado'),
    path('guardadoEmpleado/', views.guardadoEmpleado,name='guardadoEmpleado'),




#Datos Se Servicios -------------------------------->
path('registrarServicio/', views.registrarServicio,name='registrarServicio'),
path('guardarServicio/', views.guardarServicio,name='guardarServicio'),
path('listarServicios/', views.listarServicios,name='listarServicios'),
path('editarServicio/<int:id>', views.editarServicio,name='editarServicio'),
path('guardarEdicionServicio/', views.guardarEdicionServicio,name='guardarEdicionServicio'),
path('eliminarServicio/<int:id>', views.eliminarServicio,name='eliminarServicio'),
    


#Datos Citas
path('agendarCita/', views.agendarCita,name='agendarCita'),
path('guardarCita/', views.guardarCita,name='guardarCita'),
path('listarCita/', views.listarCita,name='listarCita'),
path('eliminarCita/<int:id>', views.eliminarCita,name='eliminarCita'),








]

checho/models.py
from django.db import models

# Create your models here.
class Servicios(models.Model):
    nombreServicio=models.CharField(max_length=255)
    precio=models.PositiveIntegerField()

    def __str__(self) -> str:
        return self.nombreServicio

class Clientes(models.Model):

    nombre=models.CharField(max_length=100)       
    apellido=models.CharField(max_length=100)       
    numeroTelefono=models.PositiveIntegerField()
    usuario=models.CharField(max_length=100)       
    contraseña=models.CharField(max_length=100)
    rol=models.CharField(max_length=100,default="cliente")


    def __str__(self) -> str:

        return f" {self.nombre} {self.apellido}  "


class Administradores(models.Model):

    nombre=models.CharField(max_length=100)       
    apellido=models.CharField(max_length=100)       
    numeroTelefono=models.PositiveIntegerField()
    usuario=models.CharField(max_length=100)
    contraseña=models.CharField(max_length=100)
    rol=models.CharField(max_length=100,default="administrador")

    def __str__(self) -> str:

        return f" {self.nombre} {self.apellido}  "        

class Empleados(models.Model):

    nombre=models.CharField(max_length=100)       
    apellido=models.CharField(max_length=100)       
    numeroTelefono=models.PositiveIntegerField()
    usuario=models.CharField(max_length=100)
    contraseña=models.CharField(max_length=100)
    rol=models.CharField(max_length=100,default="empleado")
    administrador=models.ForeignKey(Administradores,on_delete=models.CASCADE,null=True)

    def __str__(self) -> str:

        return f" {self.nombre} {self.apellido}  "

class Citas(models.Model):

    fecha=models.DateField(auto_now_add=False)
    hora=models.TimeField(auto_now_add=False)
    estado=models.BooleanField(default=True)
    cliente=models.ForeignKey(Clientes, on_delete=models.CASCADE,null=True)
    servicio=models.ForeignKey(Servicios, on_delete=models.CASCADE,null=True)
    empleado=models.ForeignKey(Empleados, on_delete=models.CASCADE,null=True)


    def __str__(self):

        return  f"   {self.fecha} {self.hora} {self.cliente}"

checho/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.db import IntegrityError
from django.shortcuts import render,redirect
from django.urls import reverse
from django.http import HttpResponse
from  .models import *
from django.core.paginator import Paginator


# Create your views here.
#return HttpResponseRedirect(reverse('territorio:aprendiz'))
def index(request):
    return render(request, 'index.html')

# Datos del login ------------------------------------------------------
def login(request):
    return render(request, 'login/login.html')

def ingresar(request):
    if request.method == "POST":
        try:
            #capturar datos del formulario
            use = request.POST["usua"]
            pasw = request.POST["clave"]
            
            #verificar si existe en base de datos
            q = Clientes.objects.get(usuario = use, contraseña = pasw)
            
            #crear la variable de sesion
            request.session["logueo"] = [q.id,q.usuario,q.rol]

            return redirect('checho:index')
        except Clientes.DoesNotExist:
            messages.error(request, "Usuario o contraseña incorrectos...")
            return redirect('checho:login')
    else:
        messages.warning(request, "Usted no envió datos...")
        return redirect('checho:login')

def cerraSesion(request):
    try:
        del request.session["logueo"]
        messages.success(request, "Sesión cerrada correctamente!")
    except Exception as e:
        messages.error(request, "Ocurrió un error, intente de nuevo...")
    
    return redirect('checho:index')


#datos del usuario o cliente -------------------------------->
def registrarUser(request):
    return render(request, 'usuario/registrarUser.html')

def guardarUser(request):
    try:
        if request.method == 'POST':
            nom=request.POST['nombre']
            apell=request.POST['apellido']
            numTel=request.POST['telefono']
            user=request.POST['user']
            contra=request.POST['passw']

            q=Clientes.objects.create(nombre=nom,apellido=apell,numeroTelefono=numTel,usuario=user,contraseña=contra)
            messages.success(request, 'Cliente agregado')

            return  redirect('checho:listarClientes')
        else:
            
            messages.warning(request, "Usted no envio datos ")
            return redirect('checho:listarClientes') 
    except Exception as e:
        messages.error(request, "Error: " + str(e))
        return redirect('checho:listarClientes')           
    

def listarClientes(request):
    q=Clientes.objects.all()
    pag = Paginator(q, 4)   #cinco registros por página
    page_number = request.GET.get('page')
        
        #sobreescribo el query
    q = pag.get_page(page_number)
        
    contexto = {'page_obj': q}
    return render(request,'usuario/listarUsuarios.html',contexto)


def eliminarCliente(request,id):
    try: 
        q=Clientes.objects.get(id=id)

        q.delete()
        messages.success(request, 'Cliente Eliminado')
        return redirect('checho:listarClientes') 
    except Exception as e:
        return HttpResponse(e)


def editarCliente(request,id):

    client=Clientes.objects.get(id=id)

    return render(request, 'usuario/edicionCliente.html',{'client':client})


def guardarCliente(request):

    try:
        if request.method == 'POST':
            nom=request.POST['nombre']
            ape=request.POST['apellido']
            tel=request.POST['telefono']
            id=request.POST['id']

            cliente=Clientes.objects.get(id=id)

            cliente.nombre = nom
            cliente.apellido =ape
            cliente.numeroTelefono=tel

            cliente.save()

            messages.success(request, 'Cliente agregado')

            return redirect('checho:listarClientes')

        else:
            
            messages.warning(request, "Usted no envio datos ")
            return redirect('checho:listarClientes')    

    except Exception as e:
        messages.error(request, "Error: " + str(e))
        return redirect('checho:listarClientes')

#datos de Empleado ----------------------------------->
def registrarEmpleado(request):
    admin=Administradores.objects.all()
    return render(request, 'empleado/registrarEmpleado.html',{'admin':admin})

def guardarEmpleado(request):
    
    try:
        if request.method == 'POST':
            nom=request.POST['nombre']
            apell=request.POST['apellido']
            numTel=request.POST['telefono']
            user=request.POST['user']
            contra=request.POST['passw']
            administrador=request.POST['admin']

            admin=Administradores.objects.get(id=administrador)
        
            q=Empleados.objects.create(nombre=nom,apellido=apell,numeroTelefono=numTel,usuario=user,contraseña=contra,administrador=admin)
            messages.success(request, 'Empleado agregado')
            return  redirect('checho:listarEmpleados')

        else:
            messages.warning(request, "Usted no envio datos ")
            return redirect('checho:listarEmpleados')    

    except Exception as e:
        messages.error(request, "Error: " + str(e))
        return redirect('checho:listarEmpleados')


def listarEmpleados(request):
    q=Empleados.objects.all()
    admin=Administradores.objects.all()
    pag = Paginator(q, 4)   #cinco registros por página
    page_number = request.GET.get('page')
        
        #sobreescribo el query
    q = pag.get_page(page_number)
        
    contexto = {'page_obj': q,'admin': admin}
    
    return render(request, 'empleado/listarEmpleados.html',contexto)    

def eliminarEmpleado(request, id):
    try:

        emple=Empleados.objects.get(id=id)

        emple.delete()
        messages.success(request, 'Empleado eliminado')
        return redirect('checho:listarEmpleados')

    except Exception as e:
        messages.error(request, "Error: " + str(e))
        return redirect('checho:listarEmpleados')


def editarEmpleado(request, id):


    emple=Empleados.objects.get(id=id)

    admin=Administradores.objects.all()

    return render(request, 'empleado/editarEmpleado.html', {'empleado': emple,'admin': admin})


def guardadoEmpleado(request):
    
    try:
        if request.method == 'POST':
            nom=request.POST['nombre']
            ape=request.POST['apellido']
            tel=request.POST['telefono']
            id=request.POST['id']
            admin=request.POST['admin']

            ad=Administradores.objects.get(id=admin)
            emple=Empleados.objects.get(id=id)

            emple.nombre=nom
            emple.apellido=ape
            emple.numeroTelefono=tel
            emple.administrador=ad

            emple.save()
            messages.success(request, 'Empleado Guardado')
            return  redirect('checho:listarEmpleados')
        else:
            messages.warning(request, "Usted no envio datos ")
            return redirect('checho:listarEmpleados')  
            
    except Exception as e:
        messages.error(request, "Error: " + str(e))
        return redirect('checho:listarEmpleados')

def clientesBuscar (request):
    if request.method == "POST":
        
        from django.db.models import Q
        
        q = Clientes.objects.filter(
            Q(nombre__icontains = request.POST["dato"]) | 
            Q(apellido__icontains = request.POST["dato"]) 
           
        )
        
        pag = Paginator(q, 4)   #cinco registros por página
        page_number = request.GET.get('page')
        
        #sobreescribo el query
        q = pag.get_page(page_number)
        
        contexto = {'page_obj': q, "dato_buscado": request.POST["dato"]}

        return render(request,'usuario/listarClientesAjax.html',contexto)
    else:
        messages.warning(request, "Usted no envió datos...")
        return redirect('checho:listarClientes')



#datos del Administrador ------------------------------>
def registrarAdmin(request):
    return render(request, 'admin/registrarAdmin.html')    
def loginAdmin(request):
    return render(request, 'login/loginAdmin.html')   

def logearAdmin(request):
    try:
        if request.method == 'POST':
            user=request.POST['u']
            passw=request.POST['p']

            q = Administradores.objects.get(usuario = user, contraseña = passw)
            request.session["logueo"] = [q.id,q.usuario,q.rol]
            messages.success(request, 'Bienvenido')
            return  redirect('checho:index')
        else:
            messages.warning(request, "usuario o contraseña incorrectos ")
            return redirect('checho:loginAdmin')

    except Exception as e:
        messages.error(request, "Error: " + str(e))
        return redirect('checho:loginAdmin')  


def guardarAdmin(request):
    try:
        if request.method == 'POST':
            nom=request.POST['nombre']
            apell=request.POST['apellido']
            numTel=request.POST['telefono']
            user=request.POST['user']
            contra=request.POST['passw']

            q=Administradores.objects.create(nombre=nom,apellido=apell,numeroTelefono=numTel,usuario=user,contraseña=contra)

            messages.success(request, 'Administrador Guardado')
            
            return  redirect('checho:listarAdmin')
        else:
            messages.warning(request, "Usted no envio datos ")
            return redirect('checho:listarAdmin')

    except Exception as e:
        messages.error(request, "Error: " + str(e))
        return redirect('checho:listarAdmin')  

def listarAdmin(request):

    q=Administradores.objects.all()
    pag = Paginator(q, 4)   #cinco registros por página
    page_number = request.GET.get('page')
        
        #sobreescribo el query
    q = pag.get_page(page_number)
        
    contexto = {'page_obj': q}

    return render(request, 'admin/listarAdmin.html', contexto)    
def eliminarAdmin(request,id):    
    try:

checho/templates/usuario/edicionCliente.html
{% extends 'bases/base.html' %}
{% block title %}CHECHO BARBERS CLIENTES{% endblock%}

{%block content %}

<div style="text-align: center;  padding-top: 10em; ">

    <section class="container ">
        <div class=" py-3">

            <form action="{% url 'checho:guardarCliente' %}" method="post">{% csrf_token %}

                <div class="row g-3 my-5">
                    <h1 style="color: white; ">EDITAR CLIENTE</h1>
                    <div class="col">
                        <input type="text" class="form-control" value="{{client.nombre}}" name="nombre" placeholder="Nombre "
                            aria-label="First name">
                    </div>
                    <div class="col">
                        <input type="text" class="form-control" value="{{client.apellido}}" name="apellido" placeholder="Apellido"
                            aria-label="Last name">
                    </div>
                    <div class="col">
                        <input type="number" class="form-control" value="{{client.numeroTelefono}}" name="telefono" placeholder="numero de telefono"
                            aria-label="Last name">
                    </div>
                    <input type="hidden" name="id" value="{{client.id}}">
                </div>

                <div>
                    <button type="submit" class="btn btn-success">REGISTAR</button>
                </div><br>
            </form>

        </div>


    </section><br>

</div>


{%endblock%}

checho/templates/usuario/listarClientesAjax.html
{% if page_obj %}
<div style="text-align: center;  padding-top: 10em; ">

    <section class="container ">
        <div class=" py-5">
            <div style="display: flex; justify-content: space-around;">
                <input class="form-control " type="search" placeholder="Buscar" aria-label="Buscar" id="dato"
                name="dato" value="{{ dato_buscado }}"
                onkeyup="buscarCliente('{% url 'checho:clientesBuscar' %}');" style="width:50% ;">
            {% csrf_token %}
            <br/>
            {% if dato_buscado %}
                <a href="{% url 'checho:listarClientes' %}">Ver todos</a>
                <br/>
            {% endif %}

            

            <nav aria-label="..." style="z-index: 1;">
                <ul class="pagination">
                    <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
                        <a class="page-link" {% if page_obj.has_previous %} href="?page={{ page_obj.previous_page_number }}" {% endif %}>Anterior</a>            
                    </li>
            
                    {% for i in "x"|rjust:page_obj.paginator.num_pages|make_list %}
                        <li class="page-item {% if forloop.counter == page_obj.number %}active{% endif %}" aria-current="page">
                            <a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a>
                        </li>
                    {% endfor %}
            
                    <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
                        <a class="page-link" {% if page_obj.has_next %}href="?page={{ page_obj.next_page_number }}"{% endif %}>Siguiente</a>
                    </li>
                </ul>
            </nav>

            </div><br>
            


            <div id="listarServicios">
                <h1>LISTADO DE CLIENTES</h1>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>Numero de Telefono</th>
                            <th colspan="2">Opciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in page_obj %}
                        <tr>

                            <td>{{i.nombre}}</td>
                            <td>{{i.apellido}}</td>
                            <td>{{i.numeroTelefono}}</td>
                            <td><a href="{% url 'checho:editarCliente' i.id %}"><i class="fa-solid fa-pencil"></i></a>
                            </td>
                            <td><a onclick="validar('{% url 'checho:eliminarCliente' i.id %}')"><i
                                        class="fa-solid fa-trash"> </i></a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <p style="color: white;"> Pág. {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.</p>
        </div>
    </section><br>

</div>
{% else %}

<script>
    const si=confirm("No hay Datos para mostrar, Desea volver al inicio?") 
    if (si){
        location.href = "{% url 'checho:index'%}"
    }
</script>

{% endif %}

checho/templates/usuario/listarUsuarios.html
{% extends 'bases/base.html' %}
{% block title %}CHECHO BARBERS CLIENTES{% endblock%}

{%block content %}

<div id="respuesta">
{% if page_obj %}



<div style="text-align: center;  padding-top: 10em; ">

    <section class="container ">
        <div class=" py-5">
            <div style="display: flex; justify-content: space-around;">
                <input class="form-control " type="search" placeholder="Buscar" aria-label="Buscar" id="dato"
                name="dato" value="{{ dato_buscado }}"
                onkeyup="buscarCliente('{% url 'checho:clientesBuscar' %}');" style="width:50% ;">
            {% csrf_token %}
            <br/>
            {% if dato_buscado %}
                <a href="{% url 'checho:listarClientes' %}">Ver todos</a>
                <br/>
            {% endif %}

            

            <nav aria-label="..." style="z-index: 1;">
                <ul class="pagination">
                    <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
                        <a class="page-link" {% if page_obj.has_previous %} href="?page={{ page_obj.previous_page_number }}" {% endif %}>Anterior</a>            
                    </li>
            
                    {% for i in "x"|rjust:page_obj.paginator.num_pages|make_list %}
                        <li class="page-item {% if forloop.counter == page_obj.number %}active{% endif %}" aria-current="page">
                            <a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a>
                        </li>
                    {% endfor %}
            
                    <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
                        <a class="page-link" {% if page_obj.has_next %}href="?page={{ page_obj.next_page_number }}"{% endif %}>Siguiente</a>
                    </li>
                </ul>
            </nav>

            </div><br>
            


            <div id="listarServicios">
                <h1>LISTADO DE CLIENTES</h1>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>Numero de Telefono</th>
                            <th colspan="2">Opciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in page_obj %}
                        <tr>

                            <td>{{i.nombre}}</td>
                            <td>{{i.apellido}}</td>
                            <td>{{i.numeroTelefono}}</td>
                            <td><a href="{% url 'checho:editarCliente' i.id %}"><i class="fa-solid fa-pencil"></i></a>
                            </td>
                            <td><a onclick="validar('{% url 'checho:eliminarCliente' i.id %}')"><i
                                        class="fa-solid fa-trash"> </i></a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <p style="color: white;"> Pág. {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.</p>
        </div>
    </section><br>

</div>
{% else %}
    <h1>No hay datos</h1>
{% endif %}
</div>
{% endblock %}

checho/templates/usuario/registrarUser.html
{% extends 'bases/base.html' %}
{% block title %}CHECHO BARBERS REGISTRO{% endblock%}

{%block content %}

<div style="text-align: center;  padding-top: 10em; ">

    <section class="container ">
        <div class=" py-3">
            <form action="{% url 'checho:guardarUser'%}" method="post">{% csrf_token %}
                <div class="row g-3 my-5">
                    <h1 style="color: white; ">REGISTAR USUARIO</h1>
                    <div class="col">
                        <input type="text" class="form-control" name="nombre" placeholder="Nombre" aria-label="First name">
                    </div>
                    <div class="col">
                        <input type="text" class="form-control"  name="apellido" placeholder="Apellido" aria-label="Last name">
                    </div>

                </div>
                <div class="row g-3 my-5">
                    <div class="col">
                        <input type="number" class="form-control" name="telefono" placeholder="Numero Telefono" aria-label="Last name">
                    </div>

                </div>
                <div class="row g-3 my-5">
                    <div class="col">
                        <input type="text" class="form-control" name="user" placeholder="Usuario" aria-label="Last name">
                    </div>
                    <div class="col">
                        <input type="password" class="form-control" name="passw" placeholder="Contraseña" aria-label="Last name">
                    </div>
                </div>

                <div>
                    <button type="submit" class="btn btn-success" style="width: 40%;">REGISTAR</button>
                </div><br>

            </form>

        </div>


    </section><br>

</div>


{%endblock%}